# Generated by Django 2.1.6 on 2019-02-15 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(db_index=True, max_length=255)),
                ('name_fr', models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor_name', models.CharField(db_index=True, max_length=255)),
                ('author_email', models.CharField(db_index=True, max_length=255)),
                ('text', models.CharField(db_index=True, max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('valid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='portfolio')),
                ('title_en', models.CharField(db_index=True, max_length=255)),
                ('title_fr', models.CharField(db_index=True, max_length=255)),
                ('content_en', models.TextField()),
                ('content_fr', models.TextField()),
                ('date', models.DateField()),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blogapp.BlogCategory')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blogapp.Post'),
        ),
    ]
