# Generated by Django 2.1.6 on 2019-02-14 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(db_index=True, max_length=255)),
                ('name_fr', models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(db_index=True, max_length=255)),
                ('title_fr', models.CharField(db_index=True, max_length=255)),
                ('subtitle_en', models.CharField(db_index=True, max_length=255)),
                ('subtitle_fr', models.CharField(db_index=True, max_length=255)),
                ('description_en', models.TextField()),
                ('description_fr', models.TextField()),
                ('link', models.CharField(default='', max_length=255)),
                ('github_link', models.CharField(default='', max_length=255)),
                ('date', models.DateField()),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='portfolioapp.PortfolioCategory')),
            ],
        ),
    ]
